# The storage

When you use pylbm, a generated code is performed using the descritpion of the scheme(s) (the velocities, the polynomials, the conserved moments, the equilibriums, ...). There are several generators already implemented

- NumPy
- Cython
- Pythran (work in progress)
- Loo.py (work in progress)

To have best performance following the generator, you need a specific storage of the moments and distribution functions arrays. For example, it is preferable to have a storage like $[n_v, n_x, n_y, n_z]$ in NumPy $n_v$ is the number of velocities and $n_x$, $n_y$ and $n_z$ the grid size. It is due to the vectorized form of the algorithm. Whereas for Cython, it is preferable to have the storage $[n_x, n_y, n_z, n_v]$ using the pull algorithm.

So, we have implemented a storage class that always gives to the user the same access to the moments and disribution functions arrays but with a different storage in memory for the generator. This class is called [Array](class_array.html#pylbm.storage.Array).

It is really simple to create an array. You just need to give

- the number of velocities,
- the global grid size,
- the size of the fictitious point in each direction,
- the order of $[n_v, n_x, n_y, n_z]$ with the following indices
    - 0: $n_v$
    - 1: $n_x$
    - 2: $n_y$
    - 3: $n_z$

  The default order is $[n_v, n_x, n_y, n_z]$.


- the mpi topology (optional)
- the type of the data (optional)

    The default is double
    
## 2D example

Suppose that you want to create an array with a grid size $[5, 10]$ and $9$ velocities with $1$ cell in each direction for the fictitious domain.

In [25]:
from pylbm.storage import Array
import numpy as np
a = Array(9, [5, 10], [1, 1])

In [28]:
for i in range(a.nv):
    a[i] = i

In [29]:
print(a[:])

[[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]]

 [[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.  

In [30]:
b = Array(9, [5, 10], [1, 1], sorder=[2, 1, 0])
for i in range(b.nv):
    b[i] = i

In [31]:
print(b[:])

[[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]]

 [[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.  

You can see that the access of the data is the same for $a$ et $b$ whereas the sorder is not the same.

If we look at the *array* attribute which is the real storage of our data

In [32]:
a.array.shape

(9, 5, 10)

In [33]:
b.array.shape

(10, 5, 9)

you can see that it is not the same and it is exactly what we want. To do that, we use the [swapaxes](http://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html) of numpy and we use this representation to have an access to our data.

## Access to the data with the conserved moments

When you discribe your scheme, you define the conserved moments. It is usefull to have a direct acces to these moments by giving their name and not their indices in the array. So, it is possible to specify where are the conserved moments in the array.

Let define conserved moments using sympy symbol.

In [35]:
import sympy
rho, u, v = sympy.symbols("rho, u, v")

We indicate to pylbm where are located these conserved moments in our array by giving a list of two elements: the first one is the scheme number and the second one the index in this scheme.

In [45]:
a.set_conserved_moments({rho: [0, 0], u: [0, 2], v: [0, 1]}, [0, 9])

In [46]:
a[rho]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [47]:
a[u]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]])

In [48]:
a[v]

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])